
import __ASTRO_IMAGE_IMPORT_1LJna2 from "@assets/images/blog/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fthird-post.md";
import __ASTRO_IMAGE_IMPORT_1Lh1Rn from "@assets/images/blog/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_Z1nPGfm from "@assets/images/blog/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fit%2Ffirst-post.md";
import __ASTRO_IMAGE_IMPORT_Z2qntXr from "@assets/images/blog/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fsecond-post.md";
import __ASTRO_IMAGE_IMPORT_1JaAdf from "@assets/images/blog/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fit%2Fsecond-post.md";
import __ASTRO_IMAGE_IMPORT_Z1c2NI0 from "@assets/images/blog/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Ffirst-post.md";
import __ASTRO_IMAGE_IMPORT_1zVuCF from "@assets/images/blog/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fit%2Fthird-post.md";
import __ASTRO_IMAGE_IMPORT_2jbYUY from "@assets/images/blog/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fit%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_ZyuDej from "@assets/images/blog/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkr%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_Z1R9u5Y from "@assets/images/blog/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkr%2Ffirst-post.md";
import __ASTRO_IMAGE_IMPORT_26dcqJ from "@assets/images/blog/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkr%2Fsecond-post.md";
import __ASTRO_IMAGE_IMPORT_16CGM3 from "@assets/images/blog/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkr%2Fthird-post.md";
export default new Map([["@assets/images/blog/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fthird-post.md", __ASTRO_IMAGE_IMPORT_1LJna2], ["@assets/images/blog/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_1Lh1Rn], ["@assets/images/blog/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fit%2Ffirst-post.md", __ASTRO_IMAGE_IMPORT_Z1nPGfm], ["@assets/images/blog/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fsecond-post.md", __ASTRO_IMAGE_IMPORT_Z2qntXr], ["@assets/images/blog/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fit%2Fsecond-post.md", __ASTRO_IMAGE_IMPORT_1JaAdf], ["@assets/images/blog/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Ffirst-post.md", __ASTRO_IMAGE_IMPORT_Z1c2NI0], ["@assets/images/blog/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fit%2Fthird-post.md", __ASTRO_IMAGE_IMPORT_1zVuCF], ["@assets/images/blog/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fit%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_2jbYUY], ["@assets/images/blog/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkr%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_ZyuDej], ["@assets/images/blog/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkr%2Ffirst-post.md", __ASTRO_IMAGE_IMPORT_Z1R9u5Y], ["@assets/images/blog/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkr%2Fsecond-post.md", __ASTRO_IMAGE_IMPORT_26dcqJ], ["@assets/images/blog/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkr%2Fthird-post.md", __ASTRO_IMAGE_IMPORT_16CGM3]]);
		